<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hsh</string>
	</array>
	<key>name</key>
	<string>Hush</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.hush</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.hush</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.hush</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.hush</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))\b</string>
			<key>name</key>
			<string>constant.numeric.hush</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^|;)\s*(struct(?:\s+(?:ref|bare))?)\s+([A-Za-z_0-9]+)\b</string>
			<key>name</key>
			<string>keyword.hush</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^|;)\s*(type_func|class|struct|alias|enum|when)[ \t]+([A-Za-z_0-9]+)\b</string>
			<key>name</key>
			<string>keyword.hush</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.hush</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.hush</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^|;)\s*(instance\b)\s*(?:(\().*(\))\s*)?([A-Za-z_0-9]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|;)\s*(use|type_func|class|struct|alias|enum|when|instance|struct)\b</string>
			<key>name</key>
			<string>keyword.hush</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(action)\s+([A-Za-z_0-9]+)(?:\s*(\().*(\)))?(\s*:)?\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.hush</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)(?!\s*$)(?!\s*{)|(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.hush</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^|;)\s*(action)[ \t]+([A-Za-z_0-9]+)</string>
			<key>name</key>
			<string>keyword.hush</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)((?:shared|import|export)\s*)*(?:\[.*?\]\s*)?(fn)\s+([A-Za-z_0-9]+)(?:(\[).*(\])\s*)?(?:(\()(.*?)(\))|(\*)([A-Za-z_0-9]+))(?:\s*(-&gt;))?.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>variable.hush</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.hush</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.hush</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)(?!\s*$)(?!\s*{)|(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.hush</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^|;)(?:\s*)(shared\s*)?([A-Za-z_0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.hush</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.hush</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|;)\s*shared\b</string>
			<key>name</key>
			<string>storage.modifier.hush</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|;)\s*\\.[A-Za-z_0-9]+</string>
			<key>name</key>
			<string>support.function.hush</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[/\*^&amp;%!()\[\]~\-\+=,\.:&lt;&gt;?|]</string>
			<key>name</key>
			<string>keyword.operator.hush</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.hush</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))\b</string>
					<key>name</key>
					<string>constant.numeric.hush</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[ \t]*\.[A-Za-z_0-9]+</string>
					<key>end</key>
					<string>(?=\s*($|=|;))</string>
					<key>name</key>
					<string>variable.hush</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.hush</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)([A-Za-z_0-9]+)</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|match|return|as|when|typeof|loop|break)\b</string>
					<key>name</key>
					<string>keyword.hush</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[/\*^&amp;%!()\[\]~\-\+=,\.:&lt;&gt;?|]</string>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.hush</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.hush</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.hush</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abefnprtv'"?]|[0-3]\d{,2}|[4-7]\d?|x[a-fA-F0-9]{,2}|u[a-fA-F0-9]{,4}|U[a-fA-F0-9]{,8})</string>
					<key>name</key>
					<string>constant.character.escape.hush</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.hush</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.hush</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))\b</string>
					<key>name</key>
					<string>constant.numeric.hush</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z_0-9]+</string>
					<key>name</key>
					<string>storage.type.hush</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\*\(\)]|-&gt;</string>
					<key>name</key>
					<string>keyword.operator.hush</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.hush</string>
	<key>uuid</key>
	<string>76d56f58-7ddf-4e60-a4d1-2b9d14a1be3c</string>
</dict>
</plist>
